# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: README UPDATE

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 8 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update bing wallpaper
      run: bash main.sh
    - name: Commit files
      run: |
         git config user.name ${{ secrets.USER_ID }}
         git config user.email ${{ secrets.USER_EMAIL }}
         git add .
         git commit -m "update README"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
